# Transmission server info
trconfig: {
    host: ,
    port: ,
    user: ,
    password: 
}

# RSS parse parameters
rss_config: {
    update_period: 5,
    check_duplication: False,
    keywords_list: ./keywords,
    shell_output: True
}
