# Transmission server info
trconfig: {
    host: ,
    port: ,
    user: ,
    password: 
}

# RSS parse parameters
rss_config: {
    update_period: 5,
    keywords_list: ./keywords,
    shell_output: True
}

site_config: {
    backup_site: False,
    torrent_file: False
}
